import React from 'react';

const About = props => (
  <div className="about">
    <h1 className="about-title">About AppliCan</h1>
    <br />
    <p>Welcome to AppliCAN the all new can-do job management system that's right for you! Job management: AppliCAN isn't just for searching for jobs, we're here to help you through your entire job search experience allowing easy access and visualization of your progression through many applications. Anyone can access the basic operation of searching for a job from the home page to get a first look if a job interests you you can save it to your profile after signing up and login in. Don't worry about trying to remember which version of which password you used and how many Capit3ls you needed to add, the whole process is managed painlessly through your google account with no need to register a username or password with us.</p>
    <p>The utility of AppliCAN comes in two broad categories of visualization and management.</p>
    <h2 className="about-title">Management</h2>
    <p>Management is necessary for keeping track of a large number of similar yet separate applications. This will mostly take place on the Dashboard which you can access at any time by clicking on the top right corner of the NavBar. On the Dashboard you will find all of the jobs you have saved sorted by what stage they are in. The stages are saved jobs which are jobs you have added from the search page, jobs in progress which is where the saved jobs go after clicking the plus sign next to them and of course completed jobs. Clicking on a job title on the Dashboard will take you to the job in progress page specific to that job. While the Dashboard allows an overview at a glance the jobs in progress page has all the details for the specific job. Here you will see and manage all the company contacts you have made along with their information in the add contact form. You also have the option to leave notes to yourself for every stage of the application which we have pre divided into 5 parts. Lastly you will be able to upload a cover letter for this job, in this way you need only keep the generic copy of your cover letter on your own storage space and AppliCAN will keep the personalized version exactly where it needs to be if you ever need to refer back to it.</p>
    <h2 className="about-title">Visualization</h2>
    <p>Visualization is provided in four places, three are on the Dashboard and one is on the job in progress page. At the top of the Dashboard there are two quick overviews of your profile and your progress. On the left is the delightful I-Can-Do Progress Tracker which will show a graph of your total recent activity. Directly to the right is a pie chart representation of your jobs in progress which is based on the third visual that only displays for in progress jobs, the job stepper. The job stepper is adjusted by clicking on the desired number and quickly displays the current level of completion from start to accepted offer of the job, the pie chart displays the total distribution for all your jobs. It is also possible to sort your in progress jobs by completion. The last visual appears on the jobs in progress page. The contacts table holds all of the relevant information for your communication with the company including the names positions email address and date of last communication for each contact you have made at that company.</p>
    <p>Combining searching, broad and focused information management and visual breakdowns of your information, AppliCAN aims to bring all the tools a job seeker needs right to where they should be, your fingertips! Happy Hunting!! </p> <br /><br />
  </div>
);

export default About;
