export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const UPDATE_JOB_LISTINGS = 'UPDATE_JOB_LISTINGS';
export const SAVE_JOB_LISTING = 'SAVE_JOB_LISTING';
export const QUEUE_JOB_LISTING = 'QUEUE_JOB_LISTING';
export const DELETE_JOB = 'DELETE_JOB';
export const SEE_JOB_DETAILS = 'SEE_JOB_DETAILS';
